import type {
  Agent,
  ChartDataPoint,
  Customer,
  Order,
  OrderStatus,
  StatsCard,
  SupportTicket,
  TicketPriority,
  TimeSeriesPoint,
} from "@/lib/types";

const MS_HOUR = 60 * 60 * 1000;
const MS_DAY = 24 * MS_HOUR;

function daysAgo(days: number, hourOfDay = 14): Date {
  const d = new Date(Date.now() - days * MS_DAY);
  d.setHours(hourOfDay, Math.floor((days * 17) % 60), 0, 0);
  return d;
}

function hoursAgo(hours: number): Date {
  return new Date(Date.now() - hours * MS_HOUR);
}

const regions = ["North", "South", "East", "West", "Central"] as const;

const categories = [
  "Electronics",
  "Apparel",
  "Home & Garden",
  "Sports & Outdoors",
  "Books & Media",
  "Health & Beauty",
] as const;

export const mockAgents: Agent[] = [
  {
    id: "agent-001",
    name: "Sarah Chen",
    avatar:
      "https://ui-avatars.com/api/?name=Sarah+Chen&background=4f46e5&color=fff&size=128",
    ticketsResolved: 428,
    avgResolutionHours: 3.8,
    satisfaction: 96,
    isOnline: true,
  },
  {
    id: "agent-002",
    name: "Marcus Webb",
    avatar:
      "https://ui-avatars.com/api/?name=Marcus+Webb&background=0d9488&color=fff&size=128",
    ticketsResolved: 391,
    avgResolutionHours: 4.6,
    satisfaction: 92,
    isOnline: true,
  },
  {
    id: "agent-003",
    name: "Elena Rodriguez",
    avatar:
      "https://ui-avatars.com/api/?name=Elena+Rodriguez&background=db2777&color=fff&size=128",
    ticketsResolved: 502,
    avgResolutionHours: 3.1,
    satisfaction: 98,
    isOnline: false,
  },
  {
    id: "agent-004",
    name: "James Okonkwo",
    avatar:
      "https://ui-avatars.com/api/?name=James+Okonkwo&background=ca8a04&color=fff&size=128",
    ticketsResolved: 355,
    avgResolutionHours: 5.2,
    satisfaction: 89,
    isOnline: true,
  },
  {
    id: "agent-005",
    name: "Priya Patel",
    avatar:
      "https://ui-avatars.com/api/?name=Priya+Patel&background=7c3aed&color=fff&size=128",
    ticketsResolved: 467,
    avgResolutionHours: 3.4,
    satisfaction: 95,
    isOnline: false,
  },
];

export const mockCustomers: Customer[] = [
  {
    id: "cust-001",
    name: "Daniel Frost",
    email: "daniel.frost@northline.co",
    totalOrders: 6,
    totalSpent: 1840,
    tier: "bronze",
    joinedAt: daysAgo(420),
    region: "North",
  },
  {
    id: "cust-002",
    name: "Maya Singh",
    email: "maya.singh@gmail.com",
    totalOrders: 4,
    totalSpent: 620,
    tier: "bronze",
    joinedAt: daysAgo(380),
    region: "East",
  },
  {
    id: "cust-003",
    name: "Chris Dalton",
    email: "c.dalton@rivertech.io",
    totalOrders: 11,
    totalSpent: 3210,
    tier: "silver",
    joinedAt: daysAgo(510),
    region: "South",
  },
  {
    id: "cust-004",
    name: "Riley Brooks",
    email: "riley.brooks@outlook.com",
    totalOrders: 9,
    totalSpent: 2890,
    tier: "silver",
    joinedAt: daysAgo(295),
    region: "West",
  },
  {
    id: "cust-005",
    name: "Harper Lin",
    email: "harper.lin@acmeshop.test",
    totalOrders: 15,
    totalSpent: 5120,
    tier: "silver",
    joinedAt: daysAgo(640),
    region: "Central",
  },
  {
    id: "cust-006",
    name: "Omar El-Masri",
    email: "omar.elmasri@delta.net",
    totalOrders: 22,
    totalSpent: 7840,
    tier: "gold",
    joinedAt: daysAgo(720),
    region: "East",
  },
  {
    id: "cust-007",
    name: "Vanessa Cole",
    email: "vanessa.cole@bright.co",
    totalOrders: 18,
    totalSpent: 6925,
    tier: "gold",
    joinedAt: daysAgo(540),
    region: "North",
  },
  {
    id: "cust-008",
    name: "Leo Hartmann",
    email: "leo.hartmann@posteo.de",
    totalOrders: 19,
    totalSpent: 7405,
    tier: "gold",
    joinedAt: daysAgo(600),
    region: "West",
  },
  {
    id: "cust-009",
    name: "Aisha Khan",
    email: "aisha.khan@studio.mail",
    totalOrders: 27,
    totalSpent: 11240,
    tier: "platinum",
    joinedAt: daysAgo(910),
    region: "Central",
  },
  {
    id: "cust-010",
    name: "Noah Tremblay",
    email: "noah.tremblay@icloud.com",
    totalOrders: 31,
    totalSpent: 12890,
    tier: "platinum",
    joinedAt: daysAgo(880),
    region: "South",
  },
  {
    id: "cust-011",
    name: "Grace Okoye",
    email: "grace.okoye@horizon.dev",
    totalOrders: 3,
    totalSpent: 410,
    tier: "bronze",
    joinedAt: daysAgo(120),
    region: "South",
  },
  {
    id: "cust-012",
    name: "Ethan Park",
    email: "ethan.park@fastlane.jp",
    totalOrders: 7,
    totalSpent: 1580,
    tier: "bronze",
    joinedAt: daysAgo(210),
    region: "West",
  },
  {
    id: "cust-013",
    name: "Sofia Alvarez",
    email: "sofia.alvarez@correo.mx",
    totalOrders: 12,
    totalSpent: 3955,
    tier: "silver",
    joinedAt: daysAgo(455),
    region: "East",
  },
  {
    id: "cust-014",
    name: "Malik Jefferson",
    email: "malik.jefferson@urbanfit.org",
    totalOrders: 14,
    totalSpent: 4680,
    tier: "silver",
    joinedAt: daysAgo(330),
    region: "North",
  },
  {
    id: "cust-015",
    name: "Yuki Tanaka",
    email: "yuki.tanaka@tokyo.ne.jp",
    totalOrders: 20,
    totalSpent: 7150,
    tier: "gold",
    joinedAt: daysAgo(690),
    region: "East",
  },
  {
    id: "cust-016",
    name: "Isabella Costa",
    email: "isabella.costa@sapo.pt",
    totalOrders: 17,
    totalSpent: 6380,
    tier: "gold",
    joinedAt: daysAgo(575),
    region: "South",
  },
  {
    id: "cust-017",
    name: "Henry Walsh",
    email: "henry.walsh@bluepeak.co.uk",
    totalOrders: 29,
    totalSpent: 11950,
    tier: "platinum",
    joinedAt: daysAgo(940),
    region: "West",
  },
  {
    id: "cust-018",
    name: "Zara Ahmed",
    email: "zara.ahmed@nomad.io",
    totalOrders: 26,
    totalSpent: 10520,
    tier: "platinum",
    joinedAt: daysAgo(820),
    region: "Central",
  },
  {
    id: "cust-019",
    name: "Lucas Meyer",
    email: "lucas.meyer@freemail.de",
    totalOrders: 5,
    totalSpent: 980,
    tier: "bronze",
    joinedAt: daysAgo(95),
    region: "Central",
  },
  {
    id: "cust-020",
    name: "Nina Petrov",
    email: "nina.petrova@volta.ru",
    totalOrders: 24,
    totalSpent: 9875,
    tier: "platinum",
    joinedAt: daysAgo(760),
    region: "North",
  },
];

export const mockOrders: Order[] = [
  {
    id: "ord-001",
    customerId: "cust-009",
    customerName: "Aisha Khan",
    product: "Ultrabook 14 — graphite",
    category: "Electronics",
    amount: 1649,
    status: "delivered",
    createdAt: daysAgo(56),
    updatedAt: daysAgo(48),
    region: "Central",
  },
  {
    id: "ord-002",
    customerId: "cust-004",
    customerName: "Riley Brooks",
    product: "Merino crewneck sweater",
    category: "Apparel",
    amount: 89,
    status: "shipped",
    createdAt: daysAgo(8),
    updatedAt: daysAgo(6),
    region: "West",
  },
  {
    id: "ord-003",
    customerId: "cust-015",
    customerName: "Yuki Tanaka",
    product: "Cordless stick vacuum",
    category: "Home & Garden",
    amount: 349,
    status: "processing",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
    region: "East",
  },
  {
    id: "ord-004",
    customerId: "cust-007",
    customerName: "Vanessa Cole",
    product: "Trail running shoes — wide",
    category: "Sports & Outdoors",
    amount: 149,
    status: "pending",
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(4),
    region: "North",
  },
  {
    id: "ord-005",
    customerId: "cust-002",
    customerName: "Maya Singh",
    product: "Cookbook — regional baking",
    category: "Books & Media",
    amount: 38,
    status: "cancelled",
    createdAt: daysAgo(22),
    updatedAt: daysAgo(21),
    region: "East",
  },
  {
    id: "ord-006",
    customerId: "cust-017",
    customerName: "Henry Walsh",
    product: "Vitamin D3 — 360 capsules",
    category: "Health & Beauty",
    amount: 29,
    status: "delivered",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(84),
    region: "West",
  },
  {
    id: "ord-007",
    customerId: "cust-011",
    customerName: "Grace Okoye",
    product: "Noise-cancelling earbuds",
    category: "Electronics",
    amount: 199,
    status: "delivered",
    createdAt: daysAgo(14),
    updatedAt: daysAgo(12),
    region: "South",
  },
  {
    id: "ord-008",
    customerId: "cust-020",
    customerName: "Nina Petrov",
    product: "Ceramic cookware set",
    category: "Home & Garden",
    amount: 279,
    status: "shipped",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(4),
    region: "North",
  },
  {
    id: "ord-009",
    customerId: "cust-005",
    customerName: "Harper Lin",
    product: "Performance fleece jacket",
    category: "Apparel",
    amount: 134,
    status: "processing",
    createdAt: daysAgo(4),
    updatedAt: daysAgo(3),
    region: "Central",
  },
  {
    id: "ord-010",
    customerId: "cust-014",
    customerName: "Malik Jefferson",
    product: "Carbon road bike helmet",
    category: "Sports & Outdoors",
    amount: 189,
    status: "pending",
    createdAt: hoursAgo(30),
    updatedAt: hoursAgo(28),
    region: "North",
  },
  {
    id: "ord-011",
    customerId: "cust-003",
    customerName: "Chris Dalton",
    product: "USB-C docking station",
    category: "Electronics",
    amount: 249,
    status: "delivered",
    createdAt: daysAgo(120),
    updatedAt: daysAgo(112),
    region: "South",
  },
  {
    id: "ord-012",
    customerId: "cust-018",
    customerName: "Zara Ahmed",
    product: "Minimal desk lamp — brass",
    category: "Home & Garden",
    amount: 112,
    status: "cancelled",
    createdAt: daysAgo(40),
    updatedAt: daysAgo(39),
    region: "Central",
  },
  {
    id: "ord-013",
    customerId: "cust-012",
    customerName: "Ethan Park",
    product: "Technical hiking backpack — 40L",
    category: "Sports & Outdoors",
    amount: 215,
    status: "shipped",
    createdAt: daysAgo(11),
    updatedAt: daysAgo(9),
    region: "West",
  },
  {
    id: "ord-014",
    customerId: "cust-006",
    customerName: "Omar El-Masri",
    product: "E-reader bundle + cover",
    category: "Books & Media",
    amount: 159,
    status: "delivered",
    createdAt: daysAgo(200),
    updatedAt: daysAgo(193),
    region: "East",
  },
  {
    id: "ord-015",
    customerId: "cust-008",
    customerName: "Leo Hartmann",
    product: "Electric toothbrush replacement heads",
    category: "Health & Beauty",
    amount: 44,
    status: "processing",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
    region: "West",
  },
  {
    id: "ord-016",
    customerId: "cust-001",
    customerName: "Daniel Frost",
    product: "Smart thermostat",
    category: "Electronics",
    amount: 229,
    status: "pending",
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(1),
    region: "North",
  },
  {
    id: "ord-017",
    customerId: "cust-016",
    customerName: "Isabella Costa",
    product: "Linen summer dress",
    category: "Apparel",
    amount: 98,
    status: "delivered",
    createdAt: daysAgo(65),
    updatedAt: daysAgo(60),
    region: "South",
  },
  {
    id: "ord-018",
    customerId: "cust-010",
    customerName: "Noah Tremblay",
    product: "Espresso machine — compact",
    category: "Home & Garden",
    amount: 449,
    status: "shipped",
    createdAt: daysAgo(9),
    updatedAt: daysAgo(7),
    region: "South",
  },
  {
    id: "ord-019",
    customerId: "cust-013",
    customerName: "Sofia Alvarez",
    product: "Science anthology — hardcover",
    category: "Books & Media",
    amount: 54,
    status: "cancelled",
    createdAt: daysAgo(17),
    updatedAt: daysAgo(16),
    region: "East",
  },
  {
    id: "ord-020",
    customerId: "cust-019",
    customerName: "Lucas Meyer",
    product: "Moisturizing serum — night",
    category: "Health & Beauty",
    amount: 62,
    status: "delivered",
    createdAt: daysAgo(33),
    updatedAt: daysAgo(28),
    region: "Central",
  },
  {
    id: "ord-021",
    customerId: "cust-004",
    customerName: "Riley Brooks",
    product: "4K webcam",
    category: "Electronics",
    amount: 129,
    status: "processing",
    createdAt: daysAgo(6),
    updatedAt: daysAgo(5),
    region: "West",
  },
  {
    id: "ord-022",
    customerId: "cust-009",
    customerName: "Aisha Khan",
    product: "Adjustable standing desk frame",
    category: "Home & Garden",
    amount: 519,
    status: "pending",
    createdAt: hoursAgo(8),
    updatedAt: hoursAgo(8),
    region: "Central",
  },
  {
    id: "ord-023",
    customerId: "cust-007",
    customerName: "Vanessa Cole",
    product: "Cross-training kettlebell set",
    category: "Sports & Outdoors",
    amount: 178,
    status: "delivered",
    createdAt: daysAgo(150),
    updatedAt: daysAgo(142),
    region: "North",
  },
  {
    id: "ord-024",
    customerId: "cust-005",
    customerName: "Harper Lin",
    product: "Wireless charging pad — glass",
    category: "Electronics",
    amount: 59,
    status: "shipped",
    createdAt: daysAgo(12),
    updatedAt: daysAgo(10),
    region: "Central",
  },
  {
    id: "ord-025",
    customerId: "cust-020",
    customerName: "Nina Petrov",
    product: "Wool blanket — queen",
    category: "Apparel",
    amount: 145,
    status: "cancelled",
    createdAt: daysAgo(28),
    updatedAt: daysAgo(27),
    region: "North",
  },
  {
    id: "ord-026",
    customerId: "cust-002",
    customerName: "Maya Singh",
    product: "Herbal tea sampler — 48 bags",
    category: "Health & Beauty",
    amount: 32,
    status: "delivered",
    createdAt: daysAgo(72),
    updatedAt: daysAgo(68),
    region: "East",
  },
  {
    id: "ord-027",
    customerId: "cust-015",
    customerName: "Yuki Tanaka",
    product: "Mechanical keyboard — tactile",
    category: "Electronics",
    amount: 169,
    status: "processing",
    createdAt: daysAgo(7),
    updatedAt: daysAgo(6),
    region: "East",
  },
  {
    id: "ord-028",
    customerId: "cust-008",
    customerName: "Leo Hartmann",
    product: "Graphic novel collection — signed",
    category: "Books & Media",
    amount: 72,
    status: "pending",
    createdAt: hoursAgo(42),
    updatedAt: hoursAgo(41),
    region: "West",
  },
  {
    id: "ord-029",
    customerId: "cust-006",
    customerName: "Omar El-Masri",
    product: "Insulated water bottle — 1L",
    category: "Sports & Outdoors",
    amount: 46,
    status: "delivered",
    createdAt: daysAgo(310),
    updatedAt: daysAgo(305),
    region: "East",
  },
  {
    id: "ord-030",
    customerId: "cust-001",
    customerName: "Daniel Frost",
    product: "Robot vacuum — slim profile",
    category: "Home & Garden",
    amount: 399,
    status: "shipped",
    createdAt: daysAgo(15),
    updatedAt: daysAgo(13),
    region: "North",
  },
  {
    id: "ord-031",
    customerId: "cust-014",
    customerName: "Malik Jefferson",
    product: "Oxford dress shirt — slim fit",
    category: "Apparel",
    amount: 84,
    status: "delivered",
    createdAt: daysAgo(88),
    updatedAt: daysAgo(82),
    region: "North",
  },
  {
    id: "ord-032",
    customerId: "cust-016",
    customerName: "Isabella Costa",
    product: "Portable Bluetooth speaker",
    category: "Electronics",
    amount: 119,
    status: "cancelled",
    createdAt: daysAgo(55),
    updatedAt: daysAgo(54),
    region: "South",
  },
  {
    id: "ord-033",
    customerId: "cust-012",
    customerName: "Ethan Park",
    product: "LED grow light panel",
    category: "Home & Garden",
    amount: 189,
    status: "pending",
    createdAt: hoursAgo(55),
    updatedAt: hoursAgo(54),
    region: "West",
  },
  {
    id: "ord-034",
    customerId: "cust-017",
    customerName: "Henry Walsh",
    product: "Trail map atlas — waterproof",
    category: "Books & Media",
    amount: 41,
    status: "processing",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(4),
    region: "West",
  },
  {
    id: "ord-035",
    customerId: "cust-018",
    customerName: "Zara Ahmed",
    product: "Mineral sunscreen SPF 50 — twin pack",
    category: "Health & Beauty",
    amount: 56,
    status: "shipped",
    createdAt: daysAgo(10),
    updatedAt: daysAgo(8),
    region: "Central",
  },
  {
    id: "ord-036",
    customerId: "cust-003",
    customerName: "Chris Dalton",
    product: "Curved ultrawide monitor — 34 inch",
    category: "Electronics",
    amount: 899,
    status: "delivered",
    createdAt: daysAgo(45),
    updatedAt: daysAgo(38),
    region: "South",
  },
  {
    id: "ord-037",
    customerId: "cust-011",
    customerName: "Grace Okoye",
    product: "Yoga mat — cork surface",
    category: "Sports & Outdoors",
    amount: 68,
    status: "delivered",
    createdAt: daysAgo(26),
    updatedAt: daysAgo(22),
    region: "South",
  },
  {
    id: "ord-038",
    customerId: "cust-019",
    customerName: "Lucas Meyer",
    product: "Cast iron skillet — 12 inch",
    category: "Home & Garden",
    amount: 54,
    status: "processing",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
    region: "Central",
  },
  {
    id: "ord-039",
    customerId: "cust-010",
    customerName: "Noah Tremblay",
    product: "Executive leather briefcase",
    category: "Apparel",
    amount: 289,
    status: "pending",
    createdAt: hoursAgo(12),
    updatedAt: hoursAgo(11),
    region: "South",
  },
  {
    id: "ord-040",
    customerId: "cust-013",
    customerName: "Sofia Alvarez",
    product: "Wireless gaming mouse",
    category: "Electronics",
    amount: 79,
    status: "shipped",
    createdAt: daysAgo(18),
    updatedAt: daysAgo(16),
    region: "East",
  },
];

export const mockTickets: SupportTicket[] = [
  {
    id: "tkt-001",
    orderId: "ord-004",
    customerId: "cust-007",
    customerName: "Vanessa Cole",
    subject: "Delivery window missed — need reschedule",
    priority: "high",
    status: "open",
    assignedAgent: "Sarah Chen",
    createdAt: hoursAgo(6),
    tags: ["shipping", "priority"],
  },
  {
    id: "tkt-002",
    customerId: "cust-012",
    customerName: "Ethan Park",
    subject: "Return label never arrived in inbox",
    priority: "medium",
    status: "in-progress",
    assignedAgent: "Marcus Webb",
    createdAt: hoursAgo(20),
    tags: ["returns", "email"],
  },
  {
    id: "tkt-003",
    orderId: "ord-036",
    customerId: "cust-003",
    customerName: "Chris Dalton",
    subject: "Monitor shows flicker at 144Hz after firmware update",
    priority: "urgent",
    status: "open",
    assignedAgent: "Elena Rodriguez",
    createdAt: hoursAgo(3),
    tags: ["electronics", "warranty"],
  },
  {
    id: "tkt-004",
    customerId: "cust-019",
    customerName: "Lucas Meyer",
    subject: "Question about ingredient sourcing on serum label",
    priority: "low",
    status: "resolved",
    assignedAgent: "Priya Patel",
    createdAt: daysAgo(9),
    resolvedAt: daysAgo(8),
    tags: ["product-info", "cosmetics"],
  },
  {
    id: "tkt-005",
    orderId: "ord-018",
    customerId: "cust-010",
    customerName: "Noah Tremblay",
    subject: "Espresso grounds channel clogged — first use",
    priority: "high",
    status: "in-progress",
    assignedAgent: "James Okonkwo",
    createdAt: hoursAgo(14),
    tags: ["appliances", "support-call"],
  },
  {
    id: "tkt-006",
    customerId: "cust-005",
    customerName: "Harper Lin",
    subject: "Invoice PDF missing company VAT number",
    priority: "medium",
    status: "closed",
    assignedAgent: "Sarah Chen",
    createdAt: daysAgo(44),
    resolvedAt: daysAgo(42),
    tags: ["billing", "b2b"],
  },
  {
    id: "tkt-007",
    orderId: "ord-012",
    customerId: "cust-018",
    customerName: "Zara Ahmed",
    subject: "Refund timeline after cancelled desk lamp order",
    priority: "low",
    status: "open",
    assignedAgent: "Marcus Webb",
    createdAt: hoursAgo(48),
    tags: ["refunds", "order-cancel"],
  },
  {
    id: "tkt-008",
    customerId: "cust-020",
    customerName: "Nina Petrov",
    subject: "Account locked after password reset email delay",
    priority: "urgent",
    status: "resolved",
    assignedAgent: "Elena Rodriguez",
    createdAt: daysAgo(6),
    resolvedAt: daysAgo(5),
    tags: ["account", "security"],
  },
  {
    id: "tkt-009",
    orderId: "ord-013",
    customerId: "cust-012",
    customerName: "Ethan Park",
    subject: "Strap buckle snapped on backpack — warranty claim",
    priority: "medium",
    status: "resolved",
    assignedAgent: "Priya Patel",
    createdAt: daysAgo(11),
    resolvedAt: daysAgo(9),
    tags: ["warranty", "gear"],
  },
  {
    id: "tkt-010",
    customerId: "cust-002",
    customerName: "Maya Singh",
    subject: "Wrong tracking number shown on order history page",
    priority: "low",
    status: "in-progress",
    assignedAgent: "James Okonkwo",
    createdAt: daysAgo(4),
    tags: ["website", "tracking"],
  },
  {
    id: "tkt-011",
    orderId: "ord-027",
    customerId: "cust-015",
    customerName: "Yuki Tanaka",
    subject: "Keyboard layout mismatch — received ISO instead of JIS",
    priority: "high",
    status: "closed",
    assignedAgent: "Sarah Chen",
    createdAt: daysAgo(19),
    resolvedAt: daysAgo(17),
    tags: ["exchange", "intl"],
  },
  {
    id: "tkt-012",
    customerId: "cust-008",
    customerName: "Leo Hartmann",
    subject: "Request for expedited shipping before hiking trip",
    priority: "urgent",
    status: "in-progress",
    assignedAgent: "Marcus Webb",
    createdAt: hoursAgo(9),
    tags: ["shipping", "expedite"],
  },
  {
    id: "tkt-013",
    customerId: "cust-014",
    customerName: "Malik Jefferson",
    subject: "Helmet size chart inconsistent with product page",
    priority: "low",
    status: "open",
    assignedAgent: "Elena Rodriguez",
    createdAt: daysAgo(2),
    tags: ["content", "sizing"],
  },
  {
    id: "tkt-014",
    orderId: "ord-020",
    customerId: "cust-019",
    customerName: "Lucas Meyer",
    subject: "Serum pump dispenser leaking during shipment",
    priority: "medium",
    status: "resolved",
    assignedAgent: "Priya Patel",
    createdAt: daysAgo(35),
    resolvedAt: daysAgo(33),
    tags: ["damaged-goods", "replacement"],
  },
  {
    id: "tkt-015",
    customerId: "cust-004",
    customerName: "Riley Brooks",
    subject: "Promo code from loyalty email rejected at checkout",
    priority: "high",
    status: "closed",
    assignedAgent: "James Okonkwo",
    createdAt: daysAgo(27),
    resolvedAt: daysAgo(25),
    tags: ["promotions", "checkout"],
  },
  {
    id: "tkt-016",
    orderId: "ord-008",
    customerId: "cust-020",
    customerName: "Nina Petrov",
    subject: "Cookware set arrived with chipped lid handle",
    priority: "medium",
    status: "open",
    assignedAgent: "Sarah Chen",
    createdAt: hoursAgo(30),
    tags: ["damage", "kitchen"],
  },
  {
    id: "tkt-017",
    customerId: "cust-009",
    customerName: "Aisha Khan",
    subject: "Tax exemption certificate on file — verify before next order",
    priority: "low",
    status: "closed",
    assignedAgent: "Marcus Webb",
    createdAt: daysAgo(61),
    resolvedAt: daysAgo(60),
    tags: ["tax", "enterprise"],
  },
  {
    id: "tkt-018",
    customerId: "cust-016",
    customerName: "Isabella Costa",
    subject: "Speaker pairing drops every few minutes on macOS",
    priority: "urgent",
    status: "resolved",
    assignedAgent: "Elena Rodriguez",
    createdAt: daysAgo(12),
    resolvedAt: daysAgo(11),
    tags: ["bluetooth", "audio"],
  },
  {
    id: "tkt-019",
    orderId: "ord-031",
    customerId: "cust-014",
    customerName: "Malik Jefferson",
    subject: "Shirt color differs from product photography",
    priority: "medium",
    status: "in-progress",
    assignedAgent: "Priya Patel",
    createdAt: daysAgo(7),
    tags: ["color-match", "returns"],
  },
  {
    id: "tkt-020",
    customerId: "cust-006",
    customerName: "Omar El-Masri",
    subject: "Bulk order quote for office headsets",
    priority: "low",
    status: "open",
    assignedAgent: "James Okonkwo",
    createdAt: daysAgo(1),
    tags: ["sales", "volume-pricing"],
  },
  {
    id: "tkt-021",
    customerId: "cust-011",
    customerName: "Grace Okoye",
    subject: "Need invoice resent for expense reimbursement",
    priority: "medium",
    status: "resolved",
    assignedAgent: "Sarah Chen",
    createdAt: daysAgo(16),
    resolvedAt: daysAgo(15),
    tags: ["billing", "invoice"],
  },
  {
    id: "tkt-022",
    orderId: "ord-030",
    customerId: "cust-001",
    customerName: "Daniel Frost",
    subject: "Vacuum stuck under couch — mapping route bug report",
    priority: "high",
    status: "closed",
    assignedAgent: "Marcus Webb",
    createdAt: daysAgo(13),
    resolvedAt: daysAgo(12),
    tags: ["firmware", "robotics"],
  },
  {
    id: "tkt-023",
    customerId: "cust-017",
    customerName: "Henry Walsh",
    subject: "Subscription renewal charged twice this quarter",
    priority: "urgent",
    status: "open",
    assignedAgent: "Elena Rodriguez",
    createdAt: hoursAgo(2),
    tags: ["billing", "duplicate-charge"],
  },
  {
    id: "tkt-024",
    customerId: "cust-013",
    customerName: "Sofia Alvarez",
    subject: "Gift message not printed on packing slip",
    priority: "low",
    status: "resolved",
    assignedAgent: "Priya Patel",
    createdAt: daysAgo(21),
    resolvedAt: daysAgo(20),
    tags: ["gifting", "fulfillment"],
  },
  {
    id: "tkt-025",
    orderId: "ord-035",
    customerId: "cust-018",
    customerName: "Zara Ahmed",
    subject: "Sunscreen arrived warm — storage concern",
    priority: "medium",
    status: "in-progress",
    assignedAgent: "James Okonkwo",
    createdAt: hoursAgo(22),
    tags: ["temperature", "cosmetics"],
  },
  {
    id: "tkt-026",
    customerId: "cust-001",
    customerName: "Daniel Frost",
    subject: "Thermostat schedule resets after power flicker",
    priority: "high",
    status: "resolved",
    assignedAgent: "Sarah Chen",
    createdAt: daysAgo(8),
    resolvedAt: daysAgo(7),
    tags: ["iot", "support"],
  },
  {
    id: "tkt-027",
    customerId: "cust-007",
    customerName: "Vanessa Cole",
    subject: "Loyalty tier upgrade not reflected after qualifying spend",
    priority: "medium",
    status: "closed",
    assignedAgent: "Marcus Webb",
    createdAt: daysAgo(38),
    resolvedAt: daysAgo(36),
    tags: ["loyalty", "tier"],
  },
  {
    id: "tkt-028",
    customerId: "cust-003",
    customerName: "Chris Dalton",
    subject: "Dock Ethernet drops on wake from sleep — Windows 11",
    priority: "urgent",
    status: "closed",
    assignedAgent: "Elena Rodriguez",
    createdAt: daysAgo(33),
    resolvedAt: daysAgo(31),
    tags: ["drivers", "dock"],
  },
  {
    id: "tkt-029",
    orderId: "ord-037",
    customerId: "cust-011",
    customerName: "Grace Okoye",
    subject: "Mat odor when new — safe cleaning instructions",
    priority: "low",
    status: "in-progress",
    assignedAgent: "Priya Patel",
    createdAt: daysAgo(5),
    tags: ["care-instructions", "fitness"],
  },
  {
    id: "tkt-030",
    customerId: "cust-005",
    customerName: "Harper Lin",
    subject: "Corporate procurement portal SSO login failure",
    priority: "urgent",
    status: "resolved",
    assignedAgent: "James Okonkwo",
    createdAt: daysAgo(4),
    resolvedAt: daysAgo(3),
    tags: ["sso", "enterprise-it"],
  },
];

export const mockTimeSeries: TimeSeriesPoint[] = Array.from(
  { length: 30 },
  (_, i) => {
    const dayOffset = 29 - i;
    const day = new Date(Date.now() - dayOffset * MS_DAY);
    const iso = day.toISOString().slice(0, 10);
    const wave = Math.sin((i / 30) * Math.PI * 2) * 0.35;
    const orders = Math.max(
      12,
      Math.round(26 + wave * 14 + (i % 4) * 3 + (dayOffset % 7)),
    );
    const avgOrderValue = 68 + (i % 9) * 7 + Math.round(wave * 20);
    const revenue = Math.round(orders * avgOrderValue);
    const tickets = Math.max(
      2,
      Math.round(6 + Math.cos((i / 9) * Math.PI) * 4 + (i % 3)),
    );
    return { date: iso, orders, revenue, tickets };
  },
);

const totalRevenue = mockOrders
  .filter((o) => o.status !== "cancelled")
  .reduce((sum, o) => sum + o.amount, 0);

const openTicketsCount = mockTickets.filter(
  (t) => t.status === "open" || t.status === "in-progress",
).length;

const ordersTodayIso = new Date().toISOString().slice(0, 10);
const ordersTodayCount = mockOrders.filter(
  (o) => o.createdAt.toISOString().slice(0, 10) === ordersTodayIso,
).length;

const avgResolutionHours =
  mockAgents.reduce((s, a) => s + a.avgResolutionHours, 0) /
  mockAgents.length;

export const mockStatsCards: StatsCard[] = [
  {
    title: "Total Revenue",
    value: `$${totalRevenue.toLocaleString("en-US")}`,
    change: 8.4,
    changeLabel: "vs last month",
    icon: "DollarSign",
    trend: "up",
  },
  {
    title: "Open Tickets",
    value: String(openTicketsCount),
    change: -12.1,
    changeLabel: "vs last week",
    icon: "LifeBuoy",
    trend: "down",
  },
  {
    title: "Orders Today",
    value: String(ordersTodayCount),
    change: 3.2,
    changeLabel: "vs yesterday",
    icon: "ShoppingCart",
    trend: "up",
  },
  {
    title: "Avg Resolution Time",
    value: `${avgResolutionHours.toFixed(1)}h`,
    change: -5.6,
    changeLabel: "vs last month",
    icon: "Clock",
    trend: "down",
  },
];

const orderStatuses: OrderStatus[] = [
  "pending",
  "processing",
  "shipped",
  "delivered",
  "cancelled",
];

export const ordersByStatus: ChartDataPoint[] = orderStatuses.map(
  (status) => ({
    label: status,
    value: mockOrders.filter((o) => o.status === status).length,
  }),
);

export const ticketsByPriority: ChartDataPoint[] = (
  ["low", "medium", "high", "urgent"] as TicketPriority[]
).map((p) => ({
  label: p,
  value: mockTickets.filter((t) => t.priority === p).length,
}));

export const revenueByRegion: ChartDataPoint[] = regions.map((region) => ({
  label: region,
  value: mockOrders
    .filter((o) => o.region === region && o.status !== "cancelled")
    .reduce((s, o) => s + o.amount, 0),
}));

export const revenueByCategory: ChartDataPoint[] = categories.map(
  (category) => ({
    label: category,
    value: mockOrders
      .filter((o) => o.category === category && o.status !== "cancelled")
      .reduce((s, o) => s + o.amount, 0),
  }),
);
