import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ThemeProvider } from "@/components/layout/theme-switcher/theme-provider";
import { ThemeToggle } from "@/components/layout/theme-switcher/theme-toggle";
import { cookies } from "next/headers";
import { THEME_COOKIE_KEY } from "@/lib/theme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const savedTheme = cookieStore.get(THEME_COOKIE_KEY)?.value ?? "system";

  // Resolve to a concrete class: if "system" we can't know server-side, so we
  // omit the class and let next-themes handle it (it injects a blocking script).
  // If we have "light" or "dark" from cookie, we apply it immediately.
  const themeClass =
    savedTheme === "dark" ? "dark" : savedTheme === "light" ? "light" : "";

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased ${themeClass}`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          defaultTheme={savedTheme === "system" ? "system" : savedTheme}
        >
          <TooltipProvider>
            {children}
            <ThemeToggle />
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}